name: Despliegue de Azure SQL Database

on:
  workflow_dispatch: {}


jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_IDD }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar el entorno de Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest
          
      - name: Desplegar Azure SQL Database
        run: |
          cd ${{ github.workspace }}/GitActions/terraform

          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan -auto-approve
