name: Despliegue de Azure SQL Database

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar el entorno de Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Iniciar sesión en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Desplegar Azure SQL Database
        run: |
          cd ${{ github.workspace }}/GitActions/terraform

          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan -auto-approve
