on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        enable-AzPSSession: true

      # Deploy Bicep file        
    - name: bicep-build-output
      uses: Azure/bicep-build-action@v1.0.1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        template: ./azure sql/bicep/main.bicep
    # Bicep main file path
        bicepFilePath: ./azure sql/bicep/main.bicep
    # ARM template output path
        outputFilePath: ./azure sql/bicep/main-bicepfile-sqlserver_deployment.json
