name: Terraform - AZSQL Github Actions Workflow

on:
  workflow_dispatch: {}


jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Terraform environment setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Deployment using Terraform
        run: |
          cd ${{ github.workspace }}/GitActions/terraform

          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
